config/routes.rb
Rails.application.routes.draw do
  get  'users',     to: 'users#index'
  get  'users/:id', to: 'users#show', as: 'user'
  get  'register',  to: 'users#new'
  post 'register',  to: 'users#register'
  get  'users/:id/edit',   to: 'users#edit', as: 'edit'
  post 'users/:id/update', to: 'users#update', as: 'update'
  get  'login',     to: 'users#login_form'
  post 'login',     to: 'users#login'
  post 'logout',    to: 'users#logout'

  get  'chat',     to: 'posts#index'
  get  'chat/:id', to: 'posts#show'
  post 'chat',   to: 'posts#create', as: 'create'

  root 'static#top'
  get  'about', to: 'static#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :message, {presence: true, length: {maximum: 800}}
  validates :author_id,  {presence: true}

  def jsttime
    self.created_at.in_time_zone('Asia/Tokyo').strftime("%Y-%m-%d %H:%M")
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,     {presence: true}
  validates :email,    {presence: true, uniqueness: true}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_current_user

  def set_current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def must_be_authenticated
    redirect_to(login_url) if @current_user.nil?
  end

  def must_not_be_authenticated
    redirect_to(chat_url) if @current_user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :must_be_authenticated

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(message: params[:message],
      author_id: @current_user.id.to_i)
    if @post.save
      redirect_to chat_url
    else
      @posts = Post.all.order(created_at: :desc)
      render :index
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :must_be_authenticated, {only: [:index, :show, :edit, :update, :logout]}
  before_action :must_not_be_authenticated, {only: [:new, :register, :login_form, :login]}
  before_action :ensure_same_user, {only: [:edit, :update]}

  def ensure_same_user
    redirect_to(users_url) if @current_user.id != params[:id].to_i
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def register
    @user = User.new(name: params[:name], email: params[:email],
      image_name: params[:icon],
      password: params[:password] )
    if @user.save
      session[:user_id] = @user.id
      redirect_to(chat_url)
    else
      render("users/new")
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.image_name = params[:icon]
    if @user.save
      redirect_to(user_url)
    else
      render("users/edit")
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to(chat_url)
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to(login_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleChat ver.1</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/ress/dist/ress.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div id="header-logo">
        <h1><%= link_to("SimpleChat ver.1",root_url) %></h1>
      </div>
      <div id="header-menu">
        <ul>
          <% if @current_user %>
            <li>ログイン中: <%= @current_user.name %></li>
            <li><%= link_to("投稿一覧", chat_url) %></li>
            <li><%= link_to("ユーザ一覧", users_url) %></li>
            <li><%= link_to("ログアウト", logout_url, {method: :post}) %></li>
          <% else %>
            <li><%= link_to("このアプリについて", about_url) %></li>
            <li><%= link_to("新規登録", register_url) %></li>
            <li><%= link_to("ログイン",login_url) %></li>
          <% end %>
        </ul>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>SimpleChat ver.1 made by ha4gu, powered by Ruby on Rails</p>
    </footer>

    <!--  Background pattern from Toptal Subtle Patterns
          Sneaker Mesh Fabric - Subtle Patterns | Free textures for your next web project
          https://www.toptal.com/designers/subtlepatterns/sneaker-mesh-fabric/ -->

  </body>
</html>

app/views/posts/index.html.erb
<main>
  <div class="container">
    <div id="posts">

      <div id="post-form">
        <div id="post-error">
          <ul>
            <% @post.errors.full_messages.each do |error| %>
            <li><%= error %></li>
            <% end %>
          </ul>
        </div>
        <%= form_tag(create_url) do %>
        <div id="form-message">
          <textarea id="input-message" name="message"><%= @post.message %></textarea>
        </div>
        <input id="submit-button" type="submit" value="投稿">
        <% end %>
      </div>

      <% @posts.each do |post| %>
        <% @current_user.id == post.author_id ? post_type = "my-post" : post_type = "others-post" %>
        <div class="post <%= post_type %>">
          <div class="post-content">
            <p class="post-message">
              <%= post.message %>
            </p>
            <p class="post-datetime">
              <%= link_to(post.jsttime, "/chat/#{post.id}") %>
            </p>
          </div>
          <div class="post-author">
            <% post_author = User.find(post.author_id) %>
            <img class="author-icon" src="/icons/<%= post_author.image_name %>" alt="">
            <p class="author-name">
              <%= post_author.name %>
            </p>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</main>

app/views/posts/show.html.erb
<main>
  <div class="container">
    <div id="posts">
      <% @current_user.id == @post.author_id ? post_type = "my-post" : post_type = "others-post" %>
      <div class="post <%= post_type %>">
        <div class="post-content">
          <p class="post-message">
            <%= @post.message %>
          </p>
          <p class="post-datetime">
            <%= @post.jsttime %>
          </p>
        </div>
          <div class="post-author">
            <% post_author = User.find(@post.author_id) %>
            <img class="author-icon" src="/icons/<%= post_author.image_name %>" alt="">
            <p class="author-name">
              <%= post_author.name %>
            </p>
          </div>
      </div>

    </div>
  </div>
</main>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div id="posts">

      <h2>ユーザ情報 更新</h2>
      <div id="post-error">
        <ul>
          <% @user.errors.full_messages.each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
      <%= form_tag(update_url) do %>
        <h3>ユーザ名</h3>
        <input type="text" name="name" value="<%= @user.name %>">
        <h3>メールアドレス</h3>
        <input type="text" name="email" value="<%= @user.email %>">
        <p>
          <label>アイコン
            <select name="icon">
              <option value="iconfinder_4_avatar_2754580.png">女性1</option>
              <option value="iconfinder_5_avatar_2754581.png">女性2</option>
              <option value="iconfinder_9_avatar_2754584.png">女性3</option>
              <option value="iconfinder_11_avatar_2754576.png">女性4</option>
              <option value="iconfinder_1_avatar_2754574.png">男性1</option>
              <option value="iconfinder_2_avatar_2754578.png">男性2</option>
              <option value="iconfinder_3_avatar_2754579.png">男性3</option>
              <option value="iconfinder_7_avatar_2754582.png">男性4</option>
              <option value="iconfinder_8_avatar_2754583.png">男性5</option>
              <option value="iconfinder_10_avatar_2754575.png">男性6</option>
              <option value="iconfinder_12_avatar_2754577.png">男性7</option>
            </select>
          </label>
        </p>
        <input id="submit-button" type="submit" value="更新">
      <% end %>

    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container">
    <div id="users">
      <h2>ユーザ一覧</h2>
      <% @users.each do |user| %>
        <%= link_to("/users/#{user.id}/") do %>
          <img class="icon-small" src="<%= "/icons/#{user.image_name}" %>">
          <%= "#{user.name} / #{user.email}" %>
        <% end %>
        <br>
      <% end %>

    </div>
  </div>
</main>

app/views/users/login_form.html.erb
<main>
  <div class="container">
    <div id="posts">

      <h2>ログイン</h2>
      <div id="post-error">
        <ul>
          <li><%= @error_message %></li>
        </ul>
      </div>
      <%= form_tag(login_url) do %>
        <h3>メールアドレス</h3>
        <input type="text" name="email" value="<%= @email %>">
        <h3>パスワード</h3>
        <input type="password" name="password" value="<%= @password %>">
        <input id="submit-button" type="submit" value="ログイン">
      <% end %>

    </div>
  </div>
</main>

app/views/users/new.html.erb
<main>
  <div class="container">
    <div id="posts">

      <h2>ユーザ新規登録</h2>
      <div id="post-error">
        <ul>
          <% @user.errors.full_messages.each do |error| %>
          <li><%= error %></li>
          <% end %>
        </ul>
      </div>
      <%= form_for(register_url) do %>
        <h3>ユーザ名</h3>
        <input type="text" name="name" value="<%= @user.name %>">
        <h3>メールアドレス</h3>
        <input type="text" name="email" value="<%= @user.email %>">
        <h3>パスワード</h3>
        <input type="password" name="password" value="<%= @user.password %>">
        <p>
          <label>アイコン
            <select name="icon">
              <option value="iconfinder_4_avatar_2754580.png">女性1</option>
              <option value="iconfinder_5_avatar_2754581.png">女性2</option>
              <option value="iconfinder_9_avatar_2754584.png">女性3</option>
              <option value="iconfinder_11_avatar_2754576.png">女性4</option>
              <option value="iconfinder_1_avatar_2754574.png">男性1</option>
              <option value="iconfinder_2_avatar_2754578.png">男性2</option>
              <option value="iconfinder_3_avatar_2754579.png">男性3</option>
              <option value="iconfinder_7_avatar_2754582.png">男性4</option>
              <option value="iconfinder_8_avatar_2754583.png">男性5</option>
              <option value="iconfinder_10_avatar_2754575.png">男性6</option>
              <option value="iconfinder_12_avatar_2754577.png">男性7</option>
            </select>
          </label>
        </p>
        <input id="submit-button" type="submit" value="登録">
      <% end %>

    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container">
    <div id="users">
      <h2>ユーザ情報</h2>
        ユーザ名: <%= @user.name %><br>
        メールアドレス: <%= @user.email %><br>
        アイコン: <img class="icon-medium" src="<%= "/icons/#{@user.image_name}" %>"><br>

      <% if @current_user.id == @user.id %>
      <div>
        <%= link_to("編集", edit_url) %>
      </div>
      <% end %>

    </div>
  </div>
</main>